// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ChartView: typeof import('./src/components/chartView/index.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LayoutMain: typeof import('./src/layouts/LayoutMain.vue')['default']
    LayoutMainHeader: typeof import('./src/layouts/LayoutMainHeader.vue')['default']
    LayoutMainMenu: typeof import('./src/layouts/LayoutMainMenu.vue')['default']
    NotFound: typeof import('./src/views/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestChart: typeof import('./src/views/testChart/index.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Undefined: typeof import('./src/layouts/index.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
